# Generated by Django 4.2.4 on 2023-11-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_contactcls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorycls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productcls',
            name='dateadd',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='productcls',
            name='category',
        ),
        migrations.AddField(
            model_name='productcls',
            name='category',
            field=models.ManyToManyField(to='products_app.categorycls'),
        ),
    ]
