# Generated by Django 4.2.7 on 2023-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_categorycls_productcls_dateadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcls',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='price',
            field=models.IntegerField(),
        ),
    ]
