# Generated by Django 4.2.7 on 2023-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_productcls_img_alter_productcls_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcls',
            name='code',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
