# Generated by Django 4.2.7 on 2023-12-18 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_productcls_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام ')),
                ('lname', models.CharField(max_length=50, verbose_name='فامیل ')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=150, verbose_name=' ایمیل')),
                ('password', models.CharField(max_length=50, verbose_name=' پسورد')),
                ('rpassword', models.CharField(max_length=50, verbose_name='تکرار پسورد ')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.AlterField(
            model_name='categorycls',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کتگری'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='message',
            field=models.CharField(max_length=3000, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactcls',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='category',
            field=models.ManyToManyField(to='products_app.categorycls', verbose_name='کتگری'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='code',
            field=models.CharField(default=1, max_length=150, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='dateadd',
            field=models.DateTimeField(null=True, verbose_name='تاریخ وساعت'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='des',
            field=models.CharField(max_length=2000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='img',
            field=models.ImageField(upload_to='imgs', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productcls',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.CreateModel(
            name='salecls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defa', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ')),
                ('totalprice', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت نهایی')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.clientcls', verbose_name='مشتری ')),
            ],
        ),
        migrations.CreateModel(
            name='sale_detailscls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.productcls', verbose_name='مشتری ')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.salecls', verbose_name='مشتری ')),
            ],
        ),
        migrations.CreateModel(
            name='cartcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.clientcls', verbose_name='مشتری ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.productcls', verbose_name='محصول ')),
            ],
        ),
    ]
