# Generated by Django 4.2.7 on 2023-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_clientcls_alter_categorycls_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartcls',
            options={'verbose_name': 'سبد', 'verbose_name_plural': 'سبدها'},
        ),
        migrations.AlterModelOptions(
            name='categorycls',
            options={'verbose_name': 'کتگری', 'verbose_name_plural': 'کتگری ها'},
        ),
        migrations.AlterModelOptions(
            name='contactcls',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'ارتباطات'},
        ),
        migrations.AlterModelOptions(
            name='productcls',
            options={'verbose_name': 'محصول', 'verbose_name_plural': ' محصولات'},
        ),
        migrations.AlterModelOptions(
            name='sale_detailscls',
            options={'verbose_name': 'جزییات فاکتور', 'verbose_name_plural': 'جزییات فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='salecls',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AddField(
            model_name='productcls',
            name='is_special',
            field=models.BooleanField(null=True, verbose_name='محصول ویژه'),
        ),
        migrations.AddField(
            model_name='productcls',
            name='special_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ویژه'),
        ),
    ]
