# Generated by Django 4.2.7 on 2024-01-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_alter_cartcls_options_alter_categorycls_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycls',
            options={'verbose_name': 'کتگوری', 'verbose_name_plural': 'کتگوری ها'},
        ),
        migrations.AddField(
            model_name='cartcls',
            name='send',
            field=models.IntegerField(null=True, verbose_name='هزینه ارسال '),
        ),
        migrations.AlterField(
            model_name='categorycls',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کتگوری'),
        ),
    ]
