# Generated by Django 4.2.7 on 2024-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_alter_categorycls_options_cartcls_send_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.IntegerField(null=True, verbose_name='هزینه ارسال ')),
            ],
            options={
                'verbose_name': 'هزینه ارسال',
                'verbose_name_plural': 'هزینه ارسال',
            },
        ),
        migrations.RemoveField(
            model_name='cartcls',
            name='send',
        ),
    ]
