# Generated by Django 4.2.7 on 2024-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='عکس ها')),
                ('code', models.CharField(default=1, max_length=150, verbose_name='کد محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': ' محصولات',
            },
        ),
    ]
