# Generated by Django 4.2.7 on 2024-01-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorycls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کتگوری')),
            ],
            options={
                'verbose_name': 'کتگوری',
                'verbose_name_plural': 'کتگوری ها',
            },
        ),
        migrations.AddField(
            model_name='productcls',
            name='dateadd',
            field=models.DateTimeField(null=True, verbose_name='تاریخ وساعت'),
        ),
        migrations.AddField(
            model_name='productcls',
            name='des',
            field=models.CharField(default=1, max_length=2000, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='productcls',
            name='is_special',
            field=models.BooleanField(null=True, verbose_name='محصول ویژه'),
        ),
        migrations.AddField(
            model_name='productcls',
            name='special_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ویژه'),
        ),
        migrations.AddField(
            model_name='productcls',
            name='category',
            field=models.ManyToManyField(default=1, to='product_manager.categorycls', verbose_name='کتگری'),
        ),
    ]
